---
- name: Install ZFS support
  ansible.builtin.apt:
    name:
      - zfsutils-linux
    state: present
    update_cache: true
- name: Load ZFS kernel module
  community.general.modprobe:
    name: zfs
    state: present
- name: Check existing ZFS pools
  ansible.builtin.command: zpool list -H
  register: existing_pools
  changed_when: false
  failed_when: false
- name: Import ZFS pools
  ansible.builtin.command: zpool import -fa
  when: existing_pools.stdout == ""
  register: result
  changed_when: result.rc == 0
