---
- name: Start Dockerproxy Docker container
  community.docker.docker_container:
    name: dockerproxy
    image: tecnativa/docker-socket-proxy:latest
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart_policy: unless-stopped
    ports:
      - "{{ dockerproxy_port }}:2375"
    env:
      CONTAINERS: "1"
      SERVICES: "1"
      TASKS: "1"
      POST: "0"
    memory: "{{ dockerproxy_memory }}"
