---
- name: Create Overseerr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ overseerr_config_directory }}"
- name: Start Overseerr container
  community.docker.docker_container:
    name: overseerr
    image: sctx/overseerr:latest
    pull: true
    ports:
      - "{{ overseerr_port }}:5055"
    env:
      LOG_LEVEL: info
    restart_policy: unless-stopped
    memory: "{{ overseerr_memory }}"
    user: "{{ overseerr_user_id }}:{{ overseerr_group_id }}"
    volumes:
      - "{{ overseerr_config_directory }}:/app/config:rw"
    labels:
      traefik.enable: "{{ true | string }}"
      traefik.http.routers.overseerr.rule: Host(`overseerr.{{ overseerr_domain }}`)
      traefik.http.routers.overseerr.tls: "true"
      traefik.http.routers.overseerr.tls.certresolver: letsencrypt
      traefik.http.routers.overseerr.tls.domains[0].main: "{{ overseerr_domain }}"
      traefik.http.routers.overseerr.tls.domains[0].sans: "*.{{ overseerr_domain }}"
      traefik.http.services.overseerr.loadbalancer.server.port: "5055"
