---
extends: default

ignore: |
  .ansible/
  .galaxy-collections/
  .galaxy-roles/

rules:
  line-length:
    max: 160
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  key-duplicates:
    forbid-duplicated-merge-keys: true # not enabled by default
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  quoted-strings:
    quote-type: double
    required: only-when-needed
