---
roles:
  - name: geerlingguy.docker
  - name: artis3n.tailscale
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: hifis.toolkit
  - name: vladgh.samba
