---
- name: Configure homelab server
  hosts: homelab
  become: yes
  roles:
    - role: system
    - role: backup
      vars:
        rsync_password: "{{ lookup('env', 'RSYNC_PASSWORD') }}"
        pushover_user_token: "{{ lookup('env', 'PUSHOVER_USER_TOKEN') }}"
        pushover_app_token: "{{ lookup('env', 'PUSHOVER_APP_TOKEN') }}"
    - role: samba
      vars:
        samba_password: "{{ lookup('env', 'SAMBA_PASSWORD') }}"
    - role: geerlingguy.docker
      vars:
        docker_edition: "ce"
    - role: tailscale
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--advertise-routes=192.168.1.0/24 --accept-dns=false"
    - role: nextdns
