---
# Docker application data
docker_home: "{{ homeserver_docker_home }}"

# Docker image directory
docker_image_directory: /var/lib/docker

# Docker storage driver, see https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems
docker_storage_driver: overlay2

docker_daemon_json:
  data-root: "{{ docker_image_directory }}"
  storage-driver: "{{ docker_storage_driver }}"

