---
- name: Install Samba
  apt:
    name: samba
    state: present

- name: Configure Samba
  blockinfile:
    backup: yes
    path: /etc/samba/smb.conf
    block: |
      {{ lookup('file', 'templates/smb.conf.j2') }}
  notify: Restart smbd

- name: Fetch current Samba users
  command: pdbedit -L
  register: pdb_users

- name: Set Samba password
  command:
    cmd: 'smbpasswd -s -a {{ ansible_user }}'
    stdin: |
      {{ samba_password }}
      {{ samba_password }}
  when: pdb_users.stdout.find(ansible_user) == -1
