---
- name: Create Minecraft directories
  ansible.builtin.file:
    path: "{{ minecraft_data_directory }}/{{ item.name }}"
    state: directory
    mode: "0755"
  with_items: "{{ minecraft_servers }}"
- name: Set default environment variables
  ansible.builtin.set_fact:
    default_env:
      UID: "{{ minecraft_user_id }}"
      GID: "{{ minecraft_group_id }}"
      MEMORY: 4g
      EULA: "TRUE"
- name: Start Minecraft servers
  community.docker.docker_container:
    name: minecraft-{{ item.name }}
    image: itzg/minecraft-server:latest
    pull: true
    ports:
      - "{{ item.port }}:25565"
    env: "{{ default_env | ansible.builtin.combine(item.env) }}"
    restart_policy: unless-stopped
    memory: 6g
    volumes:
      - "{{ minecraft_data_directory }}/{{ item.name }}:/data:rw"
  with_items: "{{ minecraft_servers }}"
