#!/bin/bash

PUSHOVER_URL="https://api.pushover.net/1/messages.json"

notify() {
    local message="$1"
    local title="`whoami`@${HOSTNAME}"
    local body="token=$APP_TOKEN&user=$USER_TOKEN&message=$message&title=$title"
    curl -s "$PUSHOVER_URL" -d "$body" >/dev/null
}

echo "Loading configuration..."
source "$(dirname $0)/.env"

echo "Starting rsync backup of HDD..."
sshpass -p "$RSYNC_PASSWORD" rsync -e ssh -avhH --delete --progress --exclude /disk/Downloads/ /disk/ rsync@cocoberry.local::NetBackup/zapodaj/

if [ "$?" -eq 0 ];
then
    echo "Backup of HDD finished successfully."
    notify "Backup of HDD finished successfully."
else
    echo "Backup of HDD failed."
    notify "Backup of HDD failed."
fi
