#!/bin/bash

PUSHOVER_URL="https://api.pushover.net/1/messages.json"

notify() {
    local message="$1"
    local title="`whoami`@${HOSTNAME}"
    local body="token=$APP_TOKEN&user=$USER_TOKEN&message=$message&title=$title"
    curl -s "$PUSHOVER_URL" -d "$body" >/dev/null
}

echo "Loading configuration..."
source "$(dirname $0)/.env"

echo "Starting rsync backup of Docker volumes..."
sshpass -p "$RSYNC_PASSWORD" rsync -e ssh -avhH --delete --progress /var/lib/docker/volumes/ rsync@cocoberry.local::NetBackup/docker/

if [ "$?" -eq 0 ];
then
    echo "Backup of Docker volumes finished successfully."
    notify "Backup of Docker volumes finished successfully."
else
    echo "Backup of Docker volumes failed."
    notify "Backup of Docker volumes failed."
fi
