---
- name: Install sshpass
  ansible.builtin.apt:
    name: sshpass
    state: present
- name: Copy backup script
  ansible.builtin.copy:
    src: rsync-backup.py
    dest: /usr/local/sbin/rsync-backup
    mode: "0755"
- name: Copy backup configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: /usr/local/etc/{{ item.dest }}
    mode: "0600"
  with_items:
    - src: rsync-backup.yml.j2
      dest: rsync-backup.yml
    - src: rsync-passwd.txt.j2
      dest: rsync-passwd.txt
- name: Configure cron job
  ansible.builtin.cron:
    name: Backup job
    hour: 6
    minute: 0
    job: rsync-backup 2>&1 | /usr/bin/logger -t BACKUP
