---
- name: Start Flaresolverr container
  community.docker.docker_container:
    name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    pull: true
    ports:
      - "{{ flaresolverr_port }}:8191"
    restart_policy: unless-stopped
    memory: "{{ flaresolverr_memory }}"
    labels:
      traefik.enable: "{{ true | string }}"
      traefik.http.routers.flaresolverr.rule: Host(`flaresolverr.{{ flaresolverr_domain }}`)
      traefik.http.routers.flaresolverr.tls: "true"
      traefik.http.routers.flaresolverr.tls.certresolver: letsencrypt
      traefik.http.routers.flaresolverr.tls.domains[0].main: "{{ flaresolverr_domain }}"
      traefik.http.routers.flaresolverr.tls.domains[0].sans: "*.{{ flaresolverr_domain }}"
      traefik.http.services.flaresolverr.loadbalancer.server.port: "8191"
