---
- name: Create Radarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ radarr_config_directory }}"
- name: Start Radarr container
  community.docker.docker_container:
    name: radarr
    image: linuxserver/radarr:latest
    pull: true
    ports:
      - "{{ radarr_port }}:7878"
    env:
      PUID: "{{ radarr_user_id }}"
      PGID: "{{ radarr_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ radarr_memory }}"
    volumes:
      - "{{ radarr_config_directory }}:/config:rw"
      - "{{ radarr_movies_directory }}:/movies:rw"
      - "{{ radarr_downloads_directory }}:/downloads:rw"
    labels:
      traefik.enable: "{{ true | string }}"
      traefik.http.routers.radarr.rule: Host(`radarr.{{ radarr_domain }}`)
      traefik.http.routers.radarr.tls: "true"
      traefik.http.routers.radarr.tls.certresolver: letsencrypt
      traefik.http.routers.radarr.tls.domains[0].main: "{{ radarr_domain }}"
      traefik.http.routers.radarr.tls.domains[0].sans: "*.{{ radarr_domain }}"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
