---
- name: Create Homepage directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ homepage_config_directory }}"
- name: Start Homepage container
  community.docker.docker_container:
    name: homepage
    image: gethomepage/homepage:latest
    pull: true
    ports:
      - "{{ homepage_port }}:3000"
    env:
      PUID: "{{ homepage_user_id }}"
      PGID: "{{ homepage_group_id }}"
      HOMEPAGE_ALLOWED_HOSTS: "{{ homepage_allowed_hosts }}"
    restart_policy: unless-stopped
    memory: "{{ homepage_memory }}"
    volumes:
      - "{{ homepage_config_directory }}:/app/config:rw"
    labels:
      traefik.enable: "{{ true | string }}"
      traefik.http.routers.homepage.rule: Host(`homepage.{{ homepage_domain }}`)
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.tls.certresolver: letsencrypt
      traefik.http.routers.homepage.tls.domains[0].main: "{{ homepage_domain }}"
      traefik.http.routers.homepage.tls.domains[0].sans: "*.{{ homepage_domain }}"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
