---
- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - vim
      - debconf-utils
      - fonts-terminus
      - avahi-daemon
      - zfsutils-linux
      - acpid
    state: present

- name: Configure console
  lineinfile:
    path: /etc/default/console-setup
    regexp: "{{ item.regexp }}"
    line: "{{ item.value }}"
  with_items:
    - { regexp: '^CHARMAP=', value: 'CHARMAP="UTF-8"' }
    - { regexp: '^CODESET=', value: 'CODESET="guess"' }
    - { regexp: '^FONTFACE=', value: 'FONTFACE="TerminusBold"' }
    - { regexp: '^FONTSIZE=', value: 'FONTSIZE="16x32"' }

- name: Make console changes active
  command:
    cmd: "dpkg-reconfigure -f noninteractive console-setup"

- name: Configure default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Configure sudo for admin user
  copy:
    content: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/admin
    mode: '0440'

- name: Import ZFS pools
  command:
    cmd: zpool import -a

- name: Extend LVM volumes
  shell: |
    lvextend -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv
    resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv

- name: Configure power button
  copy:
    content: "HandlePowerKey=poweroff"
    dest: /etc/systemd/logind.conf.d/poweroff.conf
    mode: '0644'
