---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: result
  until: result is succeeded
- name: Upgrade all packages # noqa package-latest
  ansible.builtin.apt:
    upgrade: true
    state: latest
- name: Install packages
  ansible.builtin.apt:
    name: "{{ system_extra_packages }}"
    state: present
  register: result
  until: result is succeeded
- name: Set login banner
  ansible.builtin.copy:
    src: motd.txt
    dest: /etc/motd
    mode: "0644"
- name: Set default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim.basic
