---
- name: Create Transmission directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ transmission_config_directory }}"
- name: Start Transmission container
  community.docker.docker_container:
    name: transmission
    image: linuxserver/transmission:latest
    pull: true
    env:
      PUID: "{{ transmission_user_id }}"
      PGID: "{{ transmission_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ transmission_memory }}"
    network_mode: "{{ transmission_network_mode }}"
    volumes:
      - "{{ transmission_config_directory }}:/config:rw"
      - "{{ transmission_downloads_directory }}:/downloads:rw"
      - "{{ transmission_watch_directory }}:/watch:rw"
