---
- name: Create Sonarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ sonarr_config_directory }}"
- name: Start Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    pull: true
    ports:
      - "{{ sonarr_port }}:8989"
    env:
      PUID: "{{ sonarr_user_id }}"
      PGID: "{{ sonarr_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ sonarr_memory }}"
    volumes:
      - "{{ sonarr_config_directory }}:/config:rw"
      - "{{ sonarr_tv_directory }}:/tv:rw"
      - "{{ sonarr_downloads_directory }}:/downloads:rw"
    labels:
      traefik.enable: "{{ true | string }}"
      traefik.http.routers.sonarr.rule: Host(`sonarr.{{ sonarr_domain }}`)
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr.tls.certresolver: letsencrypt
      traefik.http.routers.sonarr.tls.domains[0].main: "{{ sonarr_domain }}"
      traefik.http.routers.sonarr.tls.domains[0].sans: "*.{{ sonarr_domain }}"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
