---
homepage_memory: 1g
homepage_port: 3000
homepage_user_id: "{{ homeserver_user_id }}"
homepage_group_id: "{{ homeserver_group_id }}"
homepage_config_directory: "{{ homeserver_docker_home }}/homepage/config"
homepage_allowed_hosts: homepage.{{ homeserver_domain }}
