---
- name: Disable DNSStubListener
  ansible.builtin.copy:
    src: disable-stub.conf
    dest: /etc/systemd/resolved.conf.d/
    mode: "0644"
  register: disable_stub_config
- name: Restart systemd-resolved # noqa no-handler
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  when: disable_stub_config.changed
- name: Start NextDNS
  when: nextdns_enabled is true
  block:
    - name: Start NextDNS container
      community.docker.docker_container:
        name: nextdns
        image: nextdns/nextdns:latest
        network_mode: host
        pull: true
        restart_policy: unless-stopped
        memory: "{{ nextdns_memory }}"
        command: "{{ nextdns_command }}"
- name: Stop NextDNS
  when: nextdns_enabled is false
  block:
    - name: Stop NextDNS container
      community.docker.docker_container:
        name: nextdns
        state: absent
