---
- name: Install Python modules
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-docker
    state: present
  register: result
  until: result is succeeded
- name: Create Docker home directory
  ansible.builtin.file:
    path: "{{ docker_home }}"
    mode: "0755"
    state: directory
- name: Generate Docker daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_json | to_nice_json }}"
    mode: "0644"
  register: docker_config
- name: Restart Docker # noqa no-handler
  ansible.builtin.service:
    name: docker
    state: restarted
  when: docker_config.changed
