---
- name: Deploy Docker containers
  hosts: all
  become: true
  tasks:
    - name: Deploy NextDNS
      ansible.builtin.include_role:
        name: nextdns
    - name: Deploy Gluetun
      ansible.builtin.include_role:
        name: gluetun
    - name: Deploy Transmission
      ansible.builtin.include_role:
        name: transmission
    - name: Deploy Radarr
      ansible.builtin.include_role:
        name: radarr
    - name: Deploy Sonarr
      ansible.builtin.include_role:
        name: sonarr
    - name: Deploy Prowlarr
      ansible.builtin.include_role:
        name: prowlarr
    - name: Deploy Flaresolverr
      ansible.builtin.include_role:
        name: flaresolverr
    - name: Deploy Overseerr
      ansible.builtin.include_role:
        name: overseerr
    - name: Deploy Plex
      ansible.builtin.include_role:
        name: plex
    - name: Deploy Cloudflare DDNS
      ansible.builtin.include_role:
        name: cloudflare_ddns
    - name: Deploy Speedtest Tracker
      ansible.builtin.include_role:
        name: speedtest_tracker
    - name: Deploy Minecraft PaperMC server
      ansible.builtin.include_role:
        name: minecraft_papermc
    - name: Deploy Minecraft Cursed Walking server
      ansible.builtin.include_role:
        name: minecraft_cursed_walking
    - name: Deploy Watchtower
      ansible.builtin.include_role:
        name: watchtower
    - name: Deploy Homepage
      ansible.builtin.include_role:
        name: homepage
    - name: Deploy Traefik
      ansible.builtin.include_role:
        name: traefik
    - name: Deploy Whoami
      ansible.builtin.include_role:
        name: whoami
