---
- name: Set up Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_user }}"
