---
- name: Set up system
  hosts: homelab
  become: yes
  tasks:
    - name: Pin ZFS package version
      copy:
        dest: /etc/apt/preferences.d/90_zfs
        content: |
          Package: src:zfs-linux
          Pin: release n=bookworm-backports
          Pin-Priority: 990
    - name: Install ZFS support
      apt:
        name:
          - linux-headers-{{ ansible_kernel }}
          - dkms
          - zfsutils-linux
        state: present
        update_cache: true
    - name: Check if DKMS key has been loaded to MOK
      shell: mokutil --list-enrolled | grep -q "CN=DKMS module signing key"
      register: dkms_key_check
      failed_when: false
      changed_when: false
    - name: Import DKMS key to MOK
      expect:
        command: mokutil --import /var/lib/dkms/mok.pub
        responses:
          'input password': "abc"
          'input password again': "abc"
      when: dkms_key_check.rc != 0
    - name: Reboot the system
      shell: reboot
      async: 1
      poll: 0
      when: dkms_key_check.rc != 0
    - name: Wait for reboot to complete
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 10
        timeout: 300
      when: dkms_key_check.rc != 0
    - name: Load ZFS kernel module
      community.general.modprobe:
        name: zfs
        state: present
    - name: Check existing ZFS pools
      shell: zpool list -H
      register: existing_pools
      changed_when: false
      failed_when: false
    - name: Import ZFS pools
      shell: zpool import -fa
      when: existing_pools.stdout == ""
