---
- name: Set up Samba
  hosts: homelab
  become: true
  tasks:
    - name: Install and configure Samba
      ansible.builtin.include_role:
        name: samba
      vars:
        samba_password: "{{ lookup('env', 'SAMBA_PASSWORD') }}"
