---
- name: Set up system
  hosts: homelab
  become: true
  tasks:
    - name: Set up sshd
      ansible.builtin.include_role:
        name: sshd
    - name: Set up system basics
      ansible.builtin.include_role:
        name: system
