---
- name: Set up Tailscale
  hosts: all
  become: true
  tasks:
    - name: Install Tailscale
      ansible.builtin.include_role:
        name: artis3n.tailscale
    - name: Enable IP forwarding
      ansible.builtin.include_role:
        name: tailscale
