---
- name: Disable root access over SSH
  ansible.builtin.copy:
    content: |
      PermitRootLogin no
    dest: /etc/ssh/sshd_config.d/10-no-root.conf
    mode: "0440"
  notify: Restart sshd
- name: Disable password authentication over SSH
  ansible.builtin.copy:
    content: |
      PasswordAuthentication no
      ChallengeResponseAuthentication no
    dest: /etc/ssh/sshd_config.d/10-no-password.conf
    mode: "0440"
  notify: Restart sshd
