---
minecraft_cursed_walking_memory: 1g
minecraft_cursed_walking_port: 34219
minecraft_cursed_walking_user_id: "{{ ansible_user_id }}"
minecraft_cursed_walking_group_id: "{{ ansible_group_id }}"
minecraft_cursed_walking_data_directory: "{{ docker_home }}/minecraft-cursed-walking/data"
